= K3s on Libvirt Quickstart

== Setting up extra terraform provider

IMPORTANT: Due to an issue in the terraform provider system,
  you need to download and place the libvirt provider at a very specific
  location in your home directory before deploying K3s.
  You can find the libvirt provider version in `modules/k3s/libvirt/versions.tf`.
  To keep things simple this version will be referred to as
  `$LIBVIRT_PROVIDER_VERSION` in this documentation.
  Go to https://github.com/dmacvicar/terraform-provider-libvirt/releases/tag/v$LIBVIRT_PROVIDER_VERSION
  and find the correct link for your OS/CPU_ARCH
  (an example is `linux_amd64`, referred to as `$OS_CPU_ARCH` in the rest of this documentation).

```shell
mkdir -p ~/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/$LIBVIRT_PROVIDER_VERSION/$OS_CPU_ARCH/
mv terraform-provider-libvirt ~/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/$LIBVIRT_PROVIDER_VERSION/$OS_CPU_ARCH/terraform-provider-libvirt
```

== Prerequisites

- Access to a functional Libvirt daemon
- Knowledge of https://terraform.io[Terraform] basics

== Create your Terraform root module

Camptocamp's DevOps stack is a Terraform composition module
has to be instantiated from the Terraform root module.

Here is a minimal working example


```hcl
# terraform/main.tf

module "cluster" {
  source = "git::https://github.com/camptocamp/camptocamp-devops-stack.git//modules/k3s/libvirt?ref=master"

  cluster_name = "my-cluster"
  node_count   = 2
}
```

include::partial$pipeline_outputs.adoc[]

include::partial$tf_apply.adoc[]

include::partial$k3s_kubeconfig_keycloak.adoc[]

include::partial$wait_for_keycloak.adoc[]

include::partial$inspect_apps.adoc[]

include::partial$access_keycloak.adoc[]

include::partial$tf_destroy.adoc[]
