= Deploying the DevOps Stack to SKS
:ci-variables: exoscale
:terraform-provider: SKS
:terraform-provider-link: https://registry.terraform.io/providers/exoscale/exoscale/latest/docs

== Prerequisites

- Access to API keys allowing to create required resources in Exoscale,
- Access to GitLab or GitHub (only supported CI/CD for now),
- Knowledge of https://terraform.io[Terraform] basics


include::partial$terraform_instant_intro.adoc[]

```hcl
# terraform/main.tf

locals {
  cluster_name = "my-cluster"
}



module "cluster" {
  source = "git::https://github.com/camptocamp/devops-stack.git//modules/sks/exoscale?ref=v0.47.0"

  cluster_name = local.cluster_name
  zone         = "ch-gva-2"

  kubernetes_version = "1.21.4"

  nodepools = {
    "router-${local.cluster_name}" = {
      size          = 2
      instance_type = "standard.large"
    }
  }
}
```

include::partial$pipeline_outputs.adoc[]

include::partial$terraform_backend.adoc[]

include::partial$deploy_workstation.adoc[]



== Deploying from pipelines

When using pipelines, the DevOps Stack runs a dry-run on Merge Request and applies
the modification on commit on a protected branch.

include::partial$pipelines_gitlab.adoc[ci-variables, terraform-provider, terraform-provider-link]


include::partial$pipelines_github.adoc[ci-variables, terraform-provider, terraform-provider-link]


== Recovering the kubeconfig for SKS

. Retrieve the kubeconfig using the following command:
+
```bash
exo sks kubeconfig <CLUSTER_NAME> -z <YOUR_REGION> <A_USER_NAME> > kubeconfig.yaml
```

`A_USER_NAME` is the name of the user (certificate CN) to create for the new account associated with the config file.

You can then point to the new `kubeconfig.yaml` file using `export KUBECONFIG=$PWD/kubeconfig.yaml`.  
Then, you should be able to use `kubectl`.


include::partial$inspect_apps.adoc[]

include::partial$tf_destroy.adoc[]


== Reference

See the xref:ROOT:references/terraform_modules/sks/exoscale.adoc[Exoscale SKS reference page].
