---
spec:
  source:
    repoURL: ${repo_url}
    targetRevision: ${target_revision}

apps:
  keycloak:
    enabled: true
  olm:
    enabled: true
  minio:
    enabled: ${enable_minio}
minio:
  persistence:
    enabled: false
  accessKey: ${minio_access_key}
  secretKey: ${minio_secret_key}
  replicas: 1
  resources:
    requests:
      memory: 64Mi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - minio.apps.${base_domain}
    tls:
      - secretName: minio-tls
        hosts:
          - minio.apps.${base_domain}

argo-cd:
  configs:
    secret:
      extra:
        accounts.pipeline.tokens: '${argocd_accounts_pipeline_tokens}'
  controller:
    metrics:
      enabled: true
  dex:
    metrics:
      enabled: true
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - argocd.apps.${base_domain}
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.apps.${base_domain}
    metrics:
      enabled: true
  repoServer:
    metrics:
      enabled: true

keycloak:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: keycloak.apps.${base_domain}
        paths:
          - /
    tls:
      - secretName: keycloak-tls
        hosts:
          - keycloak.apps.${base_domain}
  service:
    annotations:
      traefik.ingress.kubernetes.io/service.serversscheme: https
  keycloakClient:
    client:
      clientId: ${clientid}
      secret: ${clientsecret}
      redirectUris:
        - https://argocd.apps.${base_domain}/auth/callback
        - https://grafana.apps.${base_domain}/login/generic_oauth
        - https://prometheus.apps.${base_domain}/oauth2/callback
        - https://alertmanager.apps.${base_domain}/oauth2/callback
  keycloakUser:
    password: "${admin_password}"

kube-prometheus-stack:
  alertmanager:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - alertmanager.apps.${base_domain}
      tls:
        - secretName: alertmanager-tls
          hosts:
            - alertmanager.apps.${base_domain}
  grafana:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - grafana.apps.${base_domain}
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.apps.${base_domain}
  prometheus:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - prometheus.apps.${base_domain}
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.apps.${base_domain}
