{{- if index $.Values "cert-manager" "azureIdentity" }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: cert-manager-binding
spec:
  azureIdentity: cert-manager
  selector: cert-manager
  weight: 0
{{- end }}
