{{- if index $.Values "cert-manager" "tlsCrt" }}
apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: cert-manager
data:
  tls.crt: {{ index $.Values "cert-manager" "tlsCrt" }}
  tls.key: {{ index $.Values "cert-manager" "tlsKey" }}
{{- end }}
