---
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: ${repo_url}
    targetRevision: ${target_revision}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

apps:
  aad-pod-identity:
    enabled: false
  apps:
    enabled: true
  argocd:
    enabled: true
  cert-manager:
    enabled: ${cert_manager.enable}
  csi-secrets-store-provider-azure:
    enabled: false
  efs-provisioner:
    enabled: false
  keycloak:
    enabled: ${keycloak.enable}
  kube-prometheus-stack:
    enabled: ${kube_prometheus_stack.enable}
  local-path-provisioner:
    enabled: false
  loki-stack:
    enabled: ${loki.enable}
  metrics-server:
    enabled: ${metrics_server.enable}
  minio:
    enabled: ${minio.enable}
  namespaces:
    enabled: true
  secrets-store-csi-driver:
    enabled: false
  traefik:
    enabled: ${traefik.enable}
  vault:
    enabled: false
  thanos:
    enabled: ${ can(metrics_archives.bucket_config) ? true : false }
  cluster-autoscaler:
    enabled: ${cluster_autoscaler.enable}

${yamlencode({"extraApps": extra_apps})}
${yamlencode({"extraAppProjects": extra_app_projects})}
${yamlencode({"extraApplicationSets": extra_application_sets})}

argo-cd:
  installCRDs: false
  configs:
    %{ if length(repositories) > 0 }
    repositoryCredentials:
      %{ for k, v in repositories }
      ${replace(k, "/[^-._a-zA-Z0-9]/", "_")}: |
        ${indent(8, v)}
      %{ endfor }
    %{ endif }
    secret:
      argocdServerAdminPassword: "$2a$10$wzUzrdx.jMb7lHIbW6VutuRpV4OnpPA3ItWBDiP04QVHfGqzAoj6i"  # argocd
      argocdServerAdminPasswordMtime: '2020-07-23T11:31:23Z'
      extra:
        oidc.default.clientSecret: "${replace(oidc.client_secret, "\"", "\\\"")}"
        accounts.pipeline.tokens: "${replace(argocd_accounts_pipeline_tokens, "\"", "\\\"")}"
        server.secretkey: "${replace(argocd_server_secretkey, "\"", "\\\"")}"
  controller:
    metrics:
      enabled: true
  dex:
    metrics:
      enabled: true
  repoServer:
    metrics:
      enabled: true
  server:
    config:
      accounts.pipeline: apiKey
    %{ if length(repositories) > 0 }
      repositories: |
      %{ for k, v in repositories }
        - url: ${k}
          sshPrivateKeySecret:
            name: argocd-repository-credentials
            key: ${replace(k, "/[^-._a-zA-Z0-9]/", "_")}
      %{ endfor }
    %{ endif }
      resource.customizations: |
        argoproj.io/Application:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            hs.message = ""
            if obj.status ~= nil then
              if obj.status.health ~= nil then
                hs.status = obj.status.health.status
                hs.message = obj.status.health.message
              end
            end
            return hs
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
      configManagementPlugins: |
        - name: kustomized-helm
          init:
            command: ["/bin/sh", "-c"]
            args: ["helm dependency build || true"]
          generate:
            command: ["/bin/sh", "-c"]
            args: ["echo \"$HELM_VALUES\" | helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE $HELM_ARGS -f - --include-crds > all.yaml && kustomize build"]
      url: "https://${argocd.domain}"
      oidc.config: |
        name: OIDC
        issuer: "${replace(oidc.issuer_url, "\"", "\\\"")}"
        clientID: "${replace(oidc.client_id, "\"", "\\\"")}"
        clientSecret: $oidc.default.clientSecret
        requestedIDTokenClaims:
          groups:
            essential: true
        requestedScopes:
          - openid
          - profile
          - email
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "${cluster_issuer}"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.allow-http: "false"
      hosts:
        - "${argocd.domain}"
        - "argocd.apps.${base_domain}"
      tls:
        - secretName: argocd-tls
          hosts:
            - "${argocd.domain}"
            - "argocd.apps.${base_domain}"
    metrics:
      enabled: true
    rbacConfig:
      policy.default: ''
      policy.csv: |
        g, pipeline, role:readonly
        g, argocd-admin, role:admin
      scopes: '[groups, cognito:groups, roles]'
%{ if !bootstrap && cluster_issuer == "ca-issuer" && keycloak.enable }
    volumeMounts:
      - name: certificate
        mountPath: /etc/ssl/certs/ca.crt
        subPath: ca.crt
    volumes:
      - name: certificate
        secret:
          secretName: argocd-tls
%{ endif }

argocd-applicationset: {}
argocd-notifications: {}

%{ if cert_manager.enable }
cert-manager: {}
%{ endif }

csi-secrets-store-provider-azure: {}

%{ if keycloak.enable }
keycloak:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "${cluster_issuer}"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.allow-http: "false"
    hosts:
      - host: "${keycloak.domain}"
        paths:
          - /
      - host: "keycloak.apps.${base_domain}"
        paths:
          - /
    tls:
      - secretName: keycloak-tls
        hosts:
          - "${keycloak.domain}"
          - "keycloak.apps.${base_domain}"
  service:
    annotations:
      traefik.ingress.kubernetes.io/service.serversscheme: https
  keycloakClient:
    client:
      clientId: "${replace(oidc.client_id, "\"", "\\\"")}"
      secret: "${replace(oidc.client_secret, "\"", "\\\"")}"
      redirectUris:
        - "https://argocd.apps.${base_domain}/auth/callback"
        - "https://${argocd.domain}/auth/callback"
        - "https://grafana.apps.${base_domain}/login/generic_oauth"
        - "https://${grafana.domain}/login/generic_oauth"
        - "https://prometheus.apps.${base_domain}/oauth2/callback"
        - "https://${prometheus.domain}/oauth2/callback"
        - "https://alertmanager.apps.${base_domain}/oauth2/callback"
        - "https://${alertmanager.domain}/oauth2/callback"
  keycloakUser:
    password: "${keycloak.admin_password}"
%{ endif }

%{ if kube_prometheus_stack.enable }
kube-prometheus-stack:
  alertmanager:
    enabled: ${ alertmanager.enable }
%{ if alertmanager.enable }
    alertmanagerSpec:
      containers:
        - args:
            - "--http-address=0.0.0.0:9095"
            - "--upstream=http://localhost:9093"
            - "--provider=oidc"
            - "--oidc-issuer-url=${replace(oidc.issuer_url, "\"", "\\\"")}"
            - "--client-id=${replace(oidc.client_id, "\"", "\\\"")}"
            - "--client-secret=${replace(oidc.client_secret, "\"", "\\\"")}"
            - "--cookie-secure=false"
            - "--cookie-secret=${replace(cookie_secret, "\"", "\\\"")}"
            - "--email-domain=*"
            - "--redirect-url=https://${alertmanager.domain}/oauth2/callback"
            %{ for arg in oidc.oauth2_proxy_extra_args }
            - ${arg}
            %{ endfor }
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
          name: alertmanager-proxy
          ports:
            - containerPort: 9095
              name: web
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "${cluster_issuer}"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.allow-http: "false"
      hosts:
        - "${alertmanager.domain}"
        - "alertmanager.apps.${base_domain}"
      tls:
        - secretName: alertmanager-tls
          hosts:
            - "${alertmanager.domain}"
            - "alertmanager.apps.${base_domain}"
    service:
      targetPort: 9095
    serviceMonitor:
      selfMonitor: false
%{ endif }  # alertmanager config

  grafana:
    enabled: ${grafana.enable}
%{ if grafana.enable }
    adminPassword: "${replace(grafana.admin_password, "\"", "\\\"")}"
    grafana.ini:
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        client_id: "${replace(oidc.client_id, "\"", "\\\"")}"
        client_secret: "${replace(oidc.client_secret, "\"", "\\\"")}"
        scopes: "openid profile email"
        auth_url: "${replace(oidc.oauth_url, "\"", "\\\"")}"
        token_url: "${replace(oidc.token_url, "\"", "\\\"")}"
        api_url: "${replace(oidc.api_url, "\"", "\\\"")}"
        %{ for k, v in grafana.generic_oauth_extra_args }
        ${k}: ${v}
        %{ endfor }
      server:
        domain: "${grafana.domain}"
        root_url: "https://%(domain)s"
    sidecar:
      datasources:
        defaultDatasourceEnabled: false
    additionalDataSources:
      - name: Prometheus
        type: prometheus
        # TODO: fix this 9091 with oauthPassThru
        #url: http://kube-prometheus-stack-prometheus:9091/
        url: ${ can(metrics_archives.bucket_config) ? "http://thanos-query.thanos:9090" : "http://kube-prometheus-stack-prometheus:9090"}
        access: proxy
        isDefault: true
        jsonData:
          tlsAuth: false
          tlsAuthWithCACert: false
          oauthPassThru: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "${cluster_issuer}"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.allow-http: "false"
      hosts:
        - "${grafana.domain}"
        - "grafana.apps.${base_domain}"
      tls:
        - secretName: grafana-tls
          hosts:
            - "grafana.apps.${base_domain}"
            - "${grafana.domain}"
%{ endif } # Grafana config

  prometheus:
    enabled: ${prometheus.enable}
    thanosService:
      enabled: ${ can(metrics_archives.bucket_config) ? true : false  }
%{ if prometheus.enable }
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "${cluster_issuer}"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.allow-http: "false"
      hosts:
        - "${prometheus.domain}"
        - "prometheus.apps.${base_domain}"
      tls:
        - secretName: prometheus-tls
          hosts:
            - "${prometheus.domain}"
            - "prometheus.apps.${base_domain}"
    prometheusSpec:
%{ if can(metrics_archives.bucket_config) }
      thanos:
        objectStorageConfig:
          key: thanos.yaml
          name: thanos-objectstorage
%{ endif }
      portName: proxy
      containers:
        - args:
            - "--http-address=0.0.0.0:9091"
            - "--upstream=http://localhost:9090"
            - "--provider=oidc"
            - "--oidc-issuer-url=${replace(oidc.issuer_url, "\"", "\\\"")}"
            - "--client-id=${replace(oidc.client_id, "\"", "\\\"")}"
            - "--client-secret=${replace(oidc.client_secret, "\"", "\\\"")}"
            - "--cookie-secure=false"
            - "--cookie-secret=${replace(cookie_secret, "\"", "\\\"")}"
            - "--email-domain=*"
            - "--redirect-url=https://${prometheus.domain}/oauth2/callback"
            %{ for arg in oidc.oauth2_proxy_extra_args }
            - ${arg}
            %{ endfor }
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
          name: prometheus-proxy
          ports:
            - containerPort: 9091
              name: proxy
      alertingEndpoints:
        - name: kube-prometheus-stack-alertmanager
          namespace: kube-prometheus-stack
          port: 9093
    service:
      port: 9091
      targetPort: 9091
      additionalPorts:
        - name: web
          port: 9090
          targetPort: 9090
    serviceMonitor:
      selfMonitor: false
    additionalPodMonitors:
      - name: alertmanager
        podMetricsEndpoints:
          - path: /metrics
            targetPort: 9093
        namespaceSelector:
          matchNames:
          - kube-prometheus-stack
        selector:
          matchLabels:
            alertmanager: kube-prometheus-stack-alertmanager
            app: alertmanager
      - name: prometheus
        podMetricsEndpoints:
          - path: /metrics
            targetPort: 9090
        namespaceSelector:
          matchNames:
          - kube-prometheus-stack
        selector:
          matchLabels:
            app: prometheus
            prometheus: kube-prometheus-stack-prometheus
%{ if can(metrics_archives.bucket_config) }
  ${ indent(4,yamlencode({"thanosObjectStorageConfig": metrics_archives.bucket_config})) }
%{ endif }
%{ endif } # Prometheus config
%{ endif } # kube-prometheus-stack config

%{ if loki.enable }
loki-stack: {}
%{ endif }

%{ if metrics_server.enable}
metrics-server: {}
%{ endif }

%{ if minio.enable }
minio:
  accessKey: "${replace(minio.access_key, "\"", "\\\"")}"
  secretKey: "${replace(minio.secret_key, "\"", "\\\"")}"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "${cluster_issuer}"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.allow-http: "false"
    hosts:
      - "${minio.domain}"
      - "minio.apps.${base_domain}"
    tls:
      - secretName: minio-tls
        hosts:
          - "${minio.domain}"
          - "minio.apps.${base_domain}"
  buckets:
    - name: "${loki.bucket_name}"
      policy: none
      purge: false
    - name: "${metrics_archives.bucket_name}"
      policy: none
      purge: false
%{ endif }

secrets-store-csi-driver: {}

%{ if traefik.enable }
traefik: {}
%{ endif }

vault: {}

%{ if can(metrics_archives.bucket_config) }
thanos:
  ${ indent(4,yamlencode({"objstoreConfig": metrics_archives.bucket_config})) }

  storegateway:
    enabled: true
    createConfigMap: true

  query:
    dnsDiscovery:
      sidecarsService: kube-prometheus-stack-thanos-discovery
      sidecarsNamespace: kube-prometheus-stack

  bucketweb:
    enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "${cluster_issuer}"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.allow-http: "false"
      hostname: "thanos-bucketweb.apps.${base_domain}"
      extraHosts:
        - name: "${metrics_archives.bucketweb_domain}"
      tls: true
      extraTls:
        - secretName: thanos-bucketweb-tls
          hosts:
            - "${metrics_archives.bucketweb_domain}"
            - "thanos-query.apps.${base_domain}"

  queryFrontend:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "${cluster_issuer}"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/ingress.allow-http: "false"
      hostname: "thanos-query.apps.${base_domain}"
      extraHosts:
        - name: "${metrics_archives.query_domain}"
      tls: true
      extraTls:
        - secretName: thanos-query-tls
          hosts:
            - "${metrics_archives.query_domain}"
            - "thanos-query.apps.${base_domain}"
%{ endif }

%{ if cluster_autoscaler.enable }
cluster-autoscaler: {}
%{ endif }
