variable "vpc_id" {}
variable "subnet_id" {}
variable "network_id" {}
variable "repo_url" {}
variable "target_revision" {}
variable "base_domain" {}
variable "key_pair" {}
variable "postinstall" {}
variable "app_of_apps_values_overrides" {}
