apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patchesJson6902:
  - target:
      group: "apiextensions.k8s.io"
      version: v1
      kind: CustomResourceDefinition
      name: "prometheuses.monitoring.coreos.com"
    patch: |-
      - op: add
        path: "/metadata/annotations"
        value:
          "argocd.argoproj.io/sync-options": "Replace=true"
