{{- if index $.Values "apps" "cluster-autoscaler" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: "devops-stack"
  source:
    chart: "cluster-autoscaler"
    repoURL: "https://kubernetes.github.io/autoscaler"
    targetRevision: "9.9.2"
    helm:
      values: |
        {{- index .Values "cluster-autoscaler" | toYaml | nindent 8 }}
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  {{- if .Values.spec.syncPolicy }}
  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
  {{- end }}
{{- end }}

