baseURL = "https://devops-stack.io/"
languageCode = "en-us"
title = "DevOps Stack"
theme = "bigspring"


[params]
author = "Camptocamp"
logo = "images/devops-stack-circle_by_c2c.png"
logo_width = "200px"

org_name = "Camptocamp"
org_logo = "images/logo/camptocamp.png"
org_logo_width = "200px"
org_url = "https://camptocamp.com"

version = "0.26.0"

google_analytics = "G-GDBX9466LL"

############################# social site ########################
[[params.social]]
title = "github"
icon = "fab fa-github"
link = "https://github.com/camptocamp"

[[params.social]]
title = "dev.to"
icon = "fab fa-dev"
link = "https://dev.to/camptocamp-ops"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/camptocamp"

[[params.social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/company/camptocamp-sa/"


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/css/all.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Docs"
pre = "<i class='fas fa-book'></i> "
url = "docs"
weight = 1

[[menu.main]]
name = "GitHub"
pre = "<i class='fab fa-github'></i> "
url = "https://github.com/camptocamp/camptocamp-devops-stack"
weight = 2

#[[menu.main]]
#name = "Contact"
#url = "contact"
#weight = 3
#
#[[menu.main]]
#name = "FAQ"
#url = "faq"
#weight = 4
#
# footer menu left
[[menu.footer_left]]
name = "About Us"
url = "https://camptocamp.com"

[[menu.footer_left]]
name = "Our Expertise"
url = "https://camptocamp.com"

[[menu.footer_left]]
name = "Our Services"
url = "https://camptocamp.com"


# footer menu middle
[[menu.footer_middle]]
name = "FacterDB"
url = "https://camptocamp.github.io/facterdb/"

[[menu.footer_middle]]
name = "Terraboard"
url = "https://terraboard.io"

[[menu.footer_middle]]
name = "Bivac"
url = "https://bivac.io"

# footer menu right
[[menu.footer_right]]
name = "Privacy Policy"
url = "privacy-policy"

[[menu.footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"

[[menu.footer_right]]
name = "FAQ"
url = "faq"

[languages.en]
footer_menu_left = "Camptocamp"
footer_menu_middle = "Our Projects"
footer_menu_right = "Support"
footer_content = "We automate your way to the Cloud"
