= General Contributing Guidelines

This document describes the general guidelines for contributing to the DevOps Stack.

The DevOps Stack is a collection of modules, each of them having its own release cycle, in order to ease the development and maintenance of each module.

== Development Workflow

When a new feature or fix is required, the typical workflow is the following:

1. You should create a new branch from the `main` branch of the module you want to work on;
2. Work and test on your branch;
3. When you think you feature/fix is ready, create a Pull Request to merge your branch into the `main` branch.

The following subsections describe some of the best practices to follow when working on the DevOps Stack.

=== Branches

. Keep the `main` branch clean, and only merge Pull Requests into it.
. Create a new branch for each Pull Request. *The name of the branch should be the Jira ticket number, followed by a short description of the work done in the branch*, for example `ISDEVOPS-185-v1-docs`. This will allow the Jira ticket to be automatically linked to the branch and the Pull Request.

=== Commit Messages

. When committing to your branch, you should follow the https://www.conventionalcommits.org/[Conventional Commits] specification. *This will also allow the automated changelog generation to work properly.*

. We use the following commit types:

.. *`feat`* - a new feature
.. *`fix`* - a bug fix
.. *`docs`* - documentation only changes
.. *`style`* - changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
.. *`refactor`* - a code change that neither fixes a bug nor adds a feature
.. *`ci`* - changes to the CI configuration files and scripts
.. *`chore`* - other changes that don't really modify the code (could be a merge commit, for example, `chore: rebase 'main' into 'ISDEVOPS-184-v1-docs' before merging PR`)

. If your commit adds a breaking change, you should add a `!` after the commit type, for example `feat!: add a breaking change`.
+
IMPORTANT: Adding a breaking change will automatically trigger a major version bump when the module is released.

. The commit scope is optional but recommended. *At least, for the modules that have variants, it is recommended to add the variant on the scope (`eks`, `aks` or `kind`).* If modifying something on the chart, you should add `chart` as the scope. 

. *_TODO Talk about the commit message body and footer._*

=== Pull Requests

. You can create Pull Requests from your branch any time during the development, but if it is not ready to be merged, you should mark it as a _Draft Pull Request_. This will prevent it from being merged by mistake while still allowing you to get feedback from other developers as well as the automated checks and documentation generation done by GitHub Actions.






_Talk about the way to write a good commit message, the way to write a good PR title and description, etc._

_Talk about where to write issues (each module) and stuff like that._

_Talk about PRs._

_Talk about the importance of squashing commits on the PR before merging._

