= Module Development

:url-template-repo: https://github.com/camptocamp/devops-stack-module-template

The DevOps Stack is separated into multiple Terraform modules, each of them containing a set of related resources. 

In order to improve the readability and maintenance of the code, this page contains some guidelines for the creation and development of modules. There is also a {url-template-repo}[repository template on GitHub] that can be used as a starting point for new modules and you can refer to it while reading this page.

== Basic Structure

A basic DevOps Stack module will usually contain the following files and folders:

[source]
----
devops-stack-module-template
├── .github
│   └── workflows
│       ├── linters.yaml
│       ├── release-please.yaml
│       └── terraform-docs.yaml
├── CODEOWNERS
├── LICENSE
├── locals.tf
├── main.tf
├── outputs.tf
├── README.adoc
├── terraform.tf
├── variables.tf
└── version.txt
----

Quick overview of each file/folder:

- `.github` - Contains the GitHub Actions workflows that are used to lint the code, generate the documentation and release the module. They are centralized on the main repository and each module calls the same workflows.
- `CODEOWNERS` - Contains the list of GitHub users that will be automatically assigned as reviewers for pull requests on the module. In our case it is the `@camptocamp/devops-stack` team.
- `LICENSE` - The license of the module. In our case it is the Apache 2.0 license.
- `README.adoc` - The documentation of the module. It is written in AsciiDoc and contains the example usage along with some explanations as well as the automatic documentation generated by Terraform Docs.
- `locals.tf` - Contains the definition of the local variables used in the module.
- `main.tf` - Contains the definition of the resources that are created by the module.
- `outputs.tf` - Contains the definition of the output variables of the module.
- `terraform.tf` - Contains the versions of the required providers.
- `variables.tf` - Contains the definition of the input variables of the module.
- `version.txt` - Contains the version of the module. You should only create it if you are creating a new module, after that it is automatically updated by the Release Please GitHub Action.

IMPORTANT: The `terraform.tf` file should only contain only the *minimum required version* of the required providers. This is to avoid incompatibilities between modules and it is the https://developer.hashicorp.com/terraform/language/providers/requirements#best-practices-for-provider-versions[recommended best practices by Terraform].

NOTE: Take care to properly describe each entry on the `variables.tf` and `outputs.tf` files. These descriptions are taken into account by Terraform Docs for the automatic documentation of the module.








== Structure For Modules With Embedded Helm Charts

[source]
----
devops-stack-module-template
├── .github
│   └── workflows
│       ├── linters.yaml
│       ├── release-please.yaml
│       └── terraform-docs.yaml
├── charts
│   └── CHART_NAME
│       ├── Chart.lock
│       ├── charts
│       │   └── CHART_NAME.tar.gz
│       ├── Chart.yaml
│       ├── templates
│       │   ├── _helpers.tpl
│       │   └── RESOURCE.yaml
│       └── values.yaml
├── CODEOWNERS
├── LICENSE
├── locals.tf
├── main.tf
├── outputs.tf
├── README.adoc
├── terraform.tf
├── variables.tf
└── version.txt
----

- `charts` - Contains the Helm chart(s) deployed by the module, if any. The chart itself refers to the chart that we really want to deploy as a dependency, which should be locate in the `charts/CHART_NAME/charts` folder. The chart package is simply downloaded manually using a `helm dependency update` and uploaded to the repository along with the rest of the code.

- `locals.tf` - Contains the definition of the local variables used in the module. It is here that we define the `helm_values` which contains the default values for the Helm chart, as needed by the module. Note that these should be written in HCL and not in YAML.

- `main.tf` - Contains the definition of the resources that are created by the module. It is here that we define the `argocd_project` and `argocd_application` resources that deploy Helm chart.








== Documentation

The specific documentation for each modules is located in its `README.adoc` file. If a module contains a variant (e.g. `eks` or `aks`), the documentation should be split into multiple files, one per variant. See the xref:contributing/documentation.adoc[Documentation] page for more information.

== Release

Each module is released and versioned separately. The release process is described in the xref:contributing/release.adoc[Release] page.







_Module creation checklist_

_Describe the structure of each module, what it should contain. Recommend a basic structure and the reasoning behind each file and folder, present the file/folder tree. Refer to examples in already existing modules._
