---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  labels:
    grafana-datasource: "1"
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-distributed-query-frontend.loki-distributed:3100
      version: 1
      isDefault: false
      jsonData:
        maxLines: 1000
