{{- if index .Values "argo-cd" "openshift" "enabled" }}
---
apiVersion: "oauth.openshift.io/v1"
kind: "OAuthClient"
metadata:
  name: "argocd"
secret: {{ index .Values "argo-cd" "configs" "secret" "extra" "oidc.default.clientSecret" | quote }}
grantMethod: prompt
redirectURIs:
  - {{ index .Values "argo-cd" "openshift" "oauthclient" "redirectUri" | quote }}
{{- end }}
