---
# -- Values passed to the loki-stack chart
loki-stack:
  loki:
    serviceName: loki-stack.loki-stack
    serviceMonitor:
      enabled: true
  promtail:
    serviceMonitor:
      enabled: true
  filebeat:
    daemonset:
      resources:
        limits:
          cpu:     1
          memory:  400Mi
        requests:
          cpu:     100m
          memory:  100Mi
    extraContainers: |
      - name: filebeat-prometheus-exporter
        image: "trustpilot/beat-exporter:0.4.0"
        ports:
          - containerPort: 9479
            protocol: TCP
            name: metrics
