{{- range $username, $infos := .Values.keycloakUsers }}
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: {{ $username }}
  labels:
    app: sso
spec:
  user:
    username: {{ $username }}
    firstName: {{ $infos.first_name }}
    lastName: {{ $infos.name }}
    email: {{ $infos.email | quote }}
    enabled: true
    emailVerified: true
    credentials:
      - temporary: false
        type: password
        value: {{ $infos.password | quote }}
    clientRoles:
      account:
        - manage-account
  realmSelector:
    matchLabels:
      app: sso
{{- end }}
