---
apiVersion: "keycloak.org/v1alpha1"
kind: "KeycloakClient"
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: "devops-stack-applications"
  labels:
    app: "sso"
spec:
  realmSelector:
    matchLabels:
      app: "sso"
  client:
    clientId: "{{ .Values.keycloakClient.client.clientId }}"
    secret: "{{ .Values.keycloakClient.client.secret }}"
    clientAuthenticatorType: "client-secret"
    standardFlowEnabled: true
    redirectUris:
      {{- toYaml .Values.keycloakClient.client.redirectUris | nindent 6}}
    defaultClientScopes:
      - "email"
      - "profile"
