---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: devops-stack
  labels:
    app: sso
spec:
  realm:
    id: devops-stack
    realm: devops-stack
    enabled: true
    displayName: devops-stack Realm
  instanceSelector:
    matchLabels:
      app: sso
