---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-ingress
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: keycloak
  selector:
    app: keycloak
    component: keycloak
