---
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: ${repo_url}
    targetRevision: ${target_revision}
  syncPolicy:
    automated:
      selfHeal: true

apps:
  apps:
    enabled: true
  argocd:
    enabled: true
  cert-manager:
    enabled: true
  efs-provisioner:
    enabled: ${enable_efs}
  keycloak:
    enabled: ${enable_keycloak}
  kube-prometheus-stack:
    enabled: true
  loki-stack:
    enabled: true
  metrics-server:
    enabled: true
  minio:
    enabled: ${enable_minio}
  namespaces:
    enabled: true
  olm:
    enabled: ${enable_olm}
  secrets-store-csi-driver:
    enabled: false
  traefik:
    enabled: true
  vault:
    enabled: false

${yamlencode({"extraApps": extra_apps})}

argo-cd:
  configs:
    secret:
      extra:
        oidc.default.clientSecret: ${client_secret}
        accounts.pipeline.tokens: '${argocd_accounts_pipeline_tokens}'
  controller:
    metrics:
      enabled: true
  dex:
    metrics:
      enabled: true
  repoServer:
    metrics:
      enabled: true
  server:
    config:
      url: https://argocd.apps.${cluster_name}.${base_domain}
      oidc.config: |
        name: OIDC
        issuer: ${oidc_issuer_url}
        clientID: ${client_id}
        clientSecret: $oidc.default.clientSecret
        requestedIDTokenClaims:
          groups:
            essential: true
        requestedScopes:
          - openid
          - profile
          - email
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ${cluster_issuer}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - argocd.apps.${base_domain}
        - argocd.apps.${cluster_name}.${base_domain}
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.apps.${base_domain}
            - argocd.apps.${cluster_name}.${base_domain}
    metrics:
      enabled: true
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, pipeline, role:readonly
        g, argocd-admin, role:admin
      scopes: '[groups, cognito:groups]'

cert-manager: {}

efs-provisioner: {}

keycloak:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: ${cluster_issuer}
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: keycloak.apps.${base_domain}
        paths:
          - /
      - host: keycloak.apps.${cluster_name}.${base_domain}
        paths:
          - /
    tls:
      - secretName: keycloak-tls
        hosts:
          - keycloak.apps.${base_domain}
          - keycloak.apps.${cluster_name}.${base_domain}
  service:
    annotations:
      traefik.ingress.kubernetes.io/service.serversscheme: https
  keycloakClient:
    client:
      clientId: ${client_id}
      secret: ${client_secret}
      redirectUris:
        - https://argocd.apps.${base_domain}/auth/callback
        - https://argocd.apps.${cluster_name}.${base_domain}/auth/callback
        - https://grafana.apps.${base_domain}/login/generic_oauth
        - https://grafana.apps.${cluster_name}.${base_domain}/login/generic_oauth
        - https://prometheus.apps.${base_domain}/oauth2/callback
        - https://prometheus.apps.${cluster_name}.${base_domain}/oauth2/callback
        - https://alertmanager.apps.${base_domain}/oauth2/callback
        - https://alertmanager.apps.${cluster_name}.${base_domain}/oauth2/callback
  keycloakUser:
    password: "${admin_password}"

kube-prometheus-stack:
  alertmanager:
    alertmanagerSpec:
      containers:
        - args:
            - --http-address=0.0.0.0:9095
            - --upstream=http://localhost:9093
            - --provider=oidc
            - --oidc-issuer-url=${oidc_issuer_url}
            - --client-id=${client_id}
            - --client-secret=${client_secret}
            - --cookie-secure=false
            - --cookie-secret=${cookie_secret}
            - --email-domain=*
            - --redirect-url=https://alertmanager.apps.${cluster_name}.${base_domain}/oauth2/callback
            %{ for arg in oauth2_proxy_extra_args }
            - ${arg}
            %{ endfor }
          image: quay.io/pusher/oauth2_proxy:v6.1.1
          name: alertmanager-proxy
          ports:
            - containerPort: 9095
              name: web
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ${cluster_issuer}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - alertmanager.apps.${base_domain}
        - alertmanager.apps.${cluster_name}.${base_domain}
      tls:
        - secretName: alertmanager-tls
          hosts:
            - alertmanager.apps.${base_domain}
            - alertmanager.apps.${cluster_name}.${base_domain}
    service:
      targetPort: 9095

  grafana:
    grafana.ini:
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        client_id: ${client_id}
        client_secret: ${client_secret}
        scopes: "openid profile email"
        auth_url: ${oauth2_oauth_url}
        token_url: ${oauth2_token_url}
        api_url: ${oauth2_api_url}
        %{ for k, v in grafana_generic_oauth_extra_args }
        ${k}: ${v}
        %{ endfor }
      server:
        domain: grafana.apps.${cluster_name}.${base_domain}
        root_url: "https://%(domain)s"
    sidecar:
      datasources:
        defaultDatasourceEnabled: false
    additionalDataSources:
      - name: Prometheus
        type: prometheus
        # TODO: fix this 9091 with oauthPassThru
        #url: http://kube-prometheus-stack-prometheus:9091/
        url: http://kube-prometheus-stack-prometheus:9090/
        access: proxy
        isDefault: true
        jsonData:
          tlsAuth: false
          tlsAuthWithCACert: false
          oauthPassThru: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ${cluster_issuer}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - grafana.apps.${base_domain}
        - grafana.apps.${cluster_name}.${base_domain}
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.apps.${base_domain}
            - grafana.apps.${cluster_name}.${base_domain}

  prometheus:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ${cluster_issuer}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - prometheus.apps.${base_domain}
        - prometheus.apps.${cluster_name}.${base_domain}
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.apps.${base_domain}
            - prometheus.apps.${cluster_name}.${base_domain}
    prometheusSpec:
      portName: proxy
      containers:
        - args:
            - --http-address=0.0.0.0:9091
            - --upstream=http://localhost:9090
            - --provider=oidc
            - --oidc-issuer-url=${oidc_issuer_url}
            - --client-id=${client_id}
            - --client-secret=${client_secret}
            - --cookie-secure=false
            - --cookie-secret=${cookie_secret}
            - --email-domain=*
            - --redirect-url=https://prometheus.apps.${cluster_name}.${base_domain}/oauth2/callback
            %{ for arg in oauth2_proxy_extra_args }
            - ${arg}
            %{ endfor }
          image: quay.io/pusher/oauth2_proxy:v6.1.1
          name: prometheus-proxy
          ports:
            - containerPort: 9091
              name: proxy
    service:
      port: 9091
      targetPort: 9091
      additionalPorts:
        - name: web
          port: 9090
          targetPort: 9090

loki-stack: {}

metrics-server: {}

%{ if enable_minio }
minio:
  accessKey: ${minio_access_key}
  secretKey: ${minio_secret_key}
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: ${cluster_issuer}
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - minio.apps.${base_domain}
      - minio.apps.${cluster_name}.${base_domain}
    tls:
      - secretName: minio-tls
        hosts:
          - minio.apps.${base_domain}
          - minio.apps.${cluster_name}.${base_domain}
  buckets:
    - name: ${loki_bucket_name}
      policy: none
      purge: false
%{ endif }

secrets-store-csi-driver: {}

traefik: {}

vault: {}
