---
apiVersion: "v2"
name: "keycloak"
version: "0"
description: |
  NOTE: This chart is enabled only when deploying DevOps Stack to K3s.

  This chart installs Keycloak for the identity and access management.
  It handles:
  
  * installation and configuration of Keycloak
  * creation `kubernetes` realm and `admin` user account under `kubernetes` realm
  * adds the following DevOps stack apps as clients to OAuth2/OIDC authentication server:
    * argocd        
    * grafana
    * prometheus
    * alertmanager
