= Deployment On Azure AKS

This tutorial shows how to deploy a DevOps Stack instance on Azure Cloud.

== Prerequisites

* Azure CLI installed (version ~>2)
* An Azure account with an active subscription.
* "Application Developer" Azure AD role assignment on the Azure AD instance the subscription trusts.
* "Owner" Azure role assignment on the subscription.

== Login to Azure from CLI

[source,bash]
----
az login
az account set --subscription <subscriptionID>
----

== State file

Throughout this tutorial, Terraform state file will be stored in an Azure Blob container of an Azure storage account. In order to do this, you need to create the remote state store first, so you'll work with a local state at the beginning.
First, Terraform apply the content of the file state.tf to create the container, the storage account and the resource group the account belongs to.
Once these resources created, you'll add the following block to terraform.tf and set the values from the previously created resources.

[source,hcl]
----
terraform {
  backend "azurerm" {
    resource_group_name  = "<resourceGroupName>"
    storage_account_name = "<storageAccountName>"
    container_name       = "<containerName>"
    key                  = "tfstate"
  }
  ...
}
----

Then, Terraform apply and you'll be propted to migrate the statefile, type yes.

== DNS

== Provisions and cluster

== Stack
