= Deployment With KinD

An example of a local deployment in KinD is provided https://github.com/camptocamp/devops-stack/tree/main/examples/kind-kind[here]. Clone this repository and modify it at your convenance.
In the folder, as in a standard https://developer.hashicorp.com/terraform/tutorials/modules/module#what-is-a-terraform-module[Terraform module], you will find the following files:

* `terraform.tf`: declaration of the Terraform providers used in this project
* `locals.tf`: local variables used in the DevOps Stacks.
* `main.tf`: definition of all deployed modules
* `s3_bucket.tf`: Configuration of the Minio bucket, used as backend for Loki and Thanos.
* `outputs.tf`: The output variables of the DevOps stack, e.g. credentials and K8s config.

== Specificities of the KinD deployment

==== Local load balancer

In order to replicate the load balancing options of cloud providers, https://metallb.universe.tf/[MetalLB] is deployed on the cluster.

==== Self-signed certificates + add secrets everywhere

All certificates are self-signed and handled by Cert Manager.

== Install requirements

For this setup, you will need:

* https://docs.docker.com/get-docker[Docker] to manage containers
* https://kind.sigs.k8s.io/[KinD] to deploy Kubernetes nodes as Docker containers
* https://www.terraform.io/[Terraform] to provision the whole architecture
* https://kubernetes.io/[Kubernetes] to interact with your cluster (optional)

== Download dependencies

Download all required providers and modules locally (in `./.terraform`):

[source,bash]
----
terraform init
----

== Deployment

* Describe the modules you want to deploy in `main.tf`, and comment out the others.

You can also add your owns Terraform modules here. A good place to start to write your own module is to clone the
https://github.com/camptocamp/devops-stack-helloworld[devops-stack-helloworld] repository and adapt it to your needs.

* Setup the variables in `locals.tf`:

[source,hcl]
----
include::example$deploy_examples/kind-kind/locals.tf[]
----

* Run `terraform init` to create the K8s nodes as Docker containers, and populate them with our services. They will be stored in the hidden folder `.terraform`.

=== Troubleshooting

==== ArgoCD: connection refused

This error happens when ArgoCD bootstraps itself.
[source,]
----
╷
│ Error: Error while waiting for application argocd to be created
│
│   with module.argocd.argocd_application.this,
│   on .terraform/modules/argocd/main.tf line 55, in resource "argocd_application" "this":
│   55: resource "argocd_application" "this" {
│
│ error while waiting for application argocd to be synced and healthy: rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:45729: connect: connection refused"
╵
----

Simply reapply the command `terraform apply`.

== Access the applications

The URLs of the applications are visibles in the ingress of the K8s cluster:

[source,bash]
----
kubectl get ingress --all-namespaces
----

For example, if the base domain name is `172-19-0-1.nip.io`, the applications are accessible at the following adresses:

----
https://grafana.apps.172-19-0-1.nip.io
https://alertmanager.apps.172-19-0-1.nip.io
https://prometheus.apps.172-19-0-1.nip.io
https://keycloak.apps.172-19-0-1.nip.io
https://minio.apps.172-19-0-1.nip.io
https://argocd.apps.172-19-0-1.nip.io
https://thanos-bucketweb.apps.172-19-0-1.nip.io
https://thanos-query.apps.172-19-0-1.nip.io
----

The applications credentials are managed by keycloak OIDC, and are written to the Terraform output:

[source,bash]
----
$ # List all outputs:
$ terraform output
keycloak_admin_credentials = <sensitive>
keycloak_users = <sensitive>
kubernetes_kubeconfig = <sensitive>
minio_root_user_credentials = <sensitive>
$ # To get the credentials for Grafana, Prometheus, etc.
$ terraform output keycloak_users
{
  "devopsadmin" = "aqhEbd3L0Msryjjp547ej7nyN6E2FllV"
}
----

== Conclusion

That's it, you have deployed the DevOps Stack locally ! For more informations, visit out https://devops-stack.io/[website], read the
https://devops-stack.io/docs/latest/[documentation] and checkout the code on
https://github.com/camptocamp/devops-stack[GitHub].
