---
argo-cd:
  controller: 
    metrics:
      serviceMonitor:
        # -- Specifies whether to enable Prometheus metrics of ArgoCD controller
        enabled: true
      rules:
        # -- Specifies whether to enable Prometheus metrics rules of ArgoCD controller
        enabled: true
        # -- Specifies Metric Rules of ArgoCD controller
        spec:
          - alert: ArgoAppMissing
            expr: |
              absent(argocd_app_info)
            for: 15m
            labels:
              severity: critical
            annotations:
              summary: "[ArgoCD] No reported applications"
              description: >
                ArgoCD has not reported any applications data for the past 15 minutes which
                means that it must be down or not functioning properly.  This needs to be
                resolved for this cloud to continue to maintain state.
          - alert: ArgoAppNotSynced
            expr: |
              argocd_app_info{sync_status!="Synced"} == 1
            for: 12h
            labels:
              severity: warning
            annotations:
              summary: "[{{`{{$labels.name}}`}}] Application not synchronized"
              description: >
                The application [{{`{{$labels.name}}`}} has not been synchronized for over
                12 hours which means that the state of this cloud has drifted away from the
                state inside Git.
  server:
    metrics:
      serviceMonitor:
        # -- Specifies whether to enable Prometheus metrics of ArgoCD Server
        enabled: true
    volumeMounts:
      - name: certificate
        mountPath: /etc/ssl/certs/ca.crt
        subPath: ca.crt
    volumes:
      - name: certificate
        secret:
          secretName: argocd-tls
  repoServer:
    metrics:
      serviceMonitor:
        # -- Specifies whether to enable Prometheus metrics of ArgoCD repoServer
        enabled: true
