---
apiVersion: "v2"
name: "csi-secrets-store-provider-azure"
version: "0"
dependencies:
  - name: "csi-secrets-store-provider-azure"
    version: "0.0.15"
    repository: "https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts"
