{{- if index $.Values "kube-prometheus-stack" "prometheus" "azureIdentity" }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: kube-prometheus-stack-prometheus
spec:
  type: 0
  resourceID: {{ index $.Values "kube-prometheus-stack" "prometheus" "azureIdentity" "resourceID" }}
  clientID: {{ index $.Values "kube-prometheus-stack" "prometheus" "azureIdentity" "clientID" }}
{{- end }}
