{{- if index $.Values "kube-prometheus-stack" "prometheus" "azureIdentity" }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: kube-prometheus-stack-prometheus-binding
spec:
  azureIdentity: kube-prometheus-stack-prometheus
  selector: kube-prometheus-stack-prometheus
  weight: 0
{{- end }}
