{{- if index $.Values "kube-prometheus-stack" "prometheus" "secretProviderClass" }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kube-prometheus-stack-prometheus
spec:
{{- index $.Values "kube-prometheus-stack" "prometheus" "secretProviderClass" | toYaml | nindent 2 }}
{{- end }}
