{{- if index $.Values "kube-prometheus-stack" "thanosObjectStorageConfig"  }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: thanos-objectstorage
stringData:
  thanos.yaml: |
   {{- index .Values "kube-prometheus-stack" "thanosObjectStorageConfig" | toYaml | nindent 4 }}
{{- end }}
