=== GitHub Actions

==== Create a new project on GitHub

Create a new project on GitHub and push your Terraform files on it.

==== Add Actions secrets

There are multiple ways to configure the
{terraform-provider-link}[Terraform {terraform-provider} provider].
You could commit the credentials in your code,
with a high potential risk of leakage,
or another simple solution is to define the required environment variables as Actions secrets.

In your project settings in Secrets Actions, create secrets for these variables:

include::partial$variables-{ci-variables}.adoc[]


==== Create GitHub Actions workflow for your project

Unfortunately, composite Actions have some limitations right now,
so we can't provide a single Action to declare in your workflow
(as we do for GitLab pipeline).
Hence, you have to create a `.github/workflows/terraform.yml` file with this content:

```yaml
---
name: 'Terraform'
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
include::partial$variables-{ci-variables}-github.adoc[]
      CAMPTOCAMP_DEVOPS_STACK_VERSION: 0.26.0
      TF_ROOT: terraform
    defaults:
      run:
        working-directory: ${{ env.TF_ROOT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.6

      - name: Terraform Format
        run: terraform fmt -check -diff -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -out plan

      - name: Generate outputs.tf
        if: github.event_name == 'pull_request'
        run: terraform-bin show -json plan | jq -r '.planned_values.outputs' > outputs.json

      - name: ArgoCD app diff with ${{ github.ref }}
        if: github.event_name == 'pull_request'
        uses: docker://argoproj/argocd:v1.7.12
        with:
          entrypoint: ./.github/scripts/app-diff.sh

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply --auto-approve

      - name: Terraform Plan
        if: github.event_name == 'push'
        run: terraform plan --detailed-exitcode -no-color

      - name: Generate outputs.tf
        if: github.event_name == 'push'
        run: terraform-bin output -json > outputs.json

      - name: Wait for App of Apps
        if: github.event_name == 'push'
        uses: docker://argoproj/argocd:v1.7.12
        with:
          entrypoint: .github/scripts/wait-for-app-of-apps.sh
```

And these two files in `.github/scripts`:

- `.github/scripts/app-diff.sh`:
+
```bash
#!/bin/sh

set -e

python3 -c "import urllib.request; print(urllib.request.urlopen('https://raw.githubusercontent.com/camptocamp/camptocamp-devops-stack/v$CAMPTOCAMP_DEVOPS_STACK_VERSION/scripts/app-diff.sh').read().decode())" | bash
```


- `.github/scripts/wait-for-app-of-apps.sh`:
+
```bash
#!/bin/sh

set -e

python3 -c "import urllib.request; print(urllib.request.urlopen('https://raw.githubusercontent.com/camptocamp/camptocamp-devops-stack/v$CAMPTOCAMP_DEVOPS_STACK_VERSION/scripts/wait-for-app-of-apps.sh').read().decode())" | bash
```

