---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: kubernetes
  labels:
    app: sso
spec:
  realm:
    id: kubernetes
    realm: kubernetes
    enabled: true
    displayName: Kubernetes Realm
  instanceSelector:
    matchLabels:
      app: sso
