---
apiVersion: "keycloak.org/v1alpha1"
kind: "Keycloak"
metadata:
  annotations:
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: "keycloak"
  labels:
    app: "sso"
spec:
  externalDatabase:
    enabled: true
  instances: 1
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: "DB_VENDOR"
          value: "h2"
        - name: "DB_ADDR"
        - name: "DB_USER"
        - name: "DB_PASSWORD"
