---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: jdoe
  labels:
    app: sso
spec:
  user:
    username: jdoe
    firstName: John
    lastName: Doe
    email: jdoe@example.com
    enabled: true
    emailVerified: true
    credentials:
      - temporary: false
        type: password
        value: {{ .Values.keycloakUser.password }}
    clientRoles:
      account:
        - manage-account
  realmSelector:
    matchLabels:
      app: sso
