argocd:
  openshift:
    enabled: true
    oauthclient:
      secret: ${openshift_oauthclient_secret}
argo-cd:
  openshift:
    enabled: true
    oauthclient:
      redirectUri: https://argocd.apps.${cluster_name}.${base_domain}/api/dex/callback
  redis:
    securityContext: false
  configs:
    secret:
      argocdServerAdminPassword: "$2a$10$wzUzrdx.jMb7lHIbW6VutuRpV4OnpPA3ItWBDiP04QVHfGqzAoj6i"  # argocd
      argocdServerAdminPasswordMtime: '2020-07-23T11:31:23Z'
  installCRDs: false
  controller:
    metrics:
      enabled: true
  dex:
    metrics:
      enabled: true
  repoServer:
    metrics:
      enabled: true
  server:
    extraArgs: []
    config:
      accounts.pipeline: apiKey
      oidc.config: ""
      url: https://argocd.apps.${cluster_name}.${base_domain}
      dex.config: |
        connectors:
          - id: "openshift"
            type: "openshift"
            name: "OpenShift"
            config:
              issuer: https://api.${cluster_name}.${base_domain}:6443
              clientID: "argocd"
              clientSecret: "${openshift_oauthclient_secret}"
              insecureCA: true
              redirectURI: https://argocd.apps.${cluster_name}.${base_domain}/api/dex/callback"
              groups:
                - "cluster-admins"
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, pipeline, role:readonly
    ingress:
      enabled: false
    route:
      enabled: true
      hostname: argocd.apps.${cluster_name}.${base_domain}
    metrics:
      enabled: true
