argocd:
  openshift:
    enabled: true
    oauthclient:
      secret: ${openshift_oauthclient_secret}
argo-cd:
  configs:
    cm:
      accounts.pipeline: apiKey
      oidc.config: ""
      url: https://argocd.apps.${cluster_name}.${base_domain}
      dex.config: |
        connectors:
          - id: "openshift"
            type: "openshift"
            name: "OpenShift"
            config:
              issuer: https://api.${cluster_name}.${base_domain}:6443
              clientID: "argocd"
              clientSecret: "${openshift_oauthclient_secret}"
              insecureCA: true
              redirectURI: https://argocd.apps.${cluster_name}.${base_domain}/api/dex/callback"
              groups:
                - "cluster-admins"
    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, pipeline, role:readonly

  openshift:
    enabled: true
    oauthclient:
      redirectUri: https://argocd.apps.${cluster_name}.${base_domain}/api/dex/callback
  redis:
    securityContext: false
  installCRDs: false
  controller:
    metrics:
      enabled: true
  dex:
    metrics:
      enabled: true
  repoServer:
    metrics:
      enabled: true
  server:
    extraArgs: []
    ingress:
      enabled: false
    route:
      enabled: true
      hostname: argocd.apps.${cluster_name}.${base_domain}
      termination_type: edge
      termination_policy: Redirect
    metrics:
      enabled: true
