{{- if index $.Values "loki-stack" "filebeat" "enabled" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: loki-stack-filebeat-metrics
  namespace: loki-stack
spec:
  namespaceSelector:
    matchNames:
      - loki-stack
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      app: loki-stack-filebeat
      release: loki-stack
{{- end }}
