---
apiVersion: "argoproj.io/v1alpha1"
kind: "AppProject"
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: "devops-stack"
  namespace: "argocd"
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: "DevOps Stack Project"
  destinations:
    - namespace: "*"
      server: "*"
  orphanedResources:
    warn: true
  sourceRepos:
    - "{{ .Values.spec.source.repoURL }}"
    - "https://github.com/keycloak/keycloak-operator.git"
    - "https://github.com/kubernetes-sigs/metrics-server.git"
    - "https://github.com/rancher/local-path-provisioner"
