---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.helm.sh/release-name: app-of-apps
    meta.helm.sh/release-namespace: argocd
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/managed-by: Helm
    argocd.argoproj.io/instance: apps
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/apps
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        {{ toYaml .Values | nindent 8 }}
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
