{{- if index $.Values "apps" "apps" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: apps
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: apps
spec:
  project: default
  source:
    path: argocd/apps
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        {{ toYaml .Values | nindent 8 }}
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}
