---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    argocd.argoproj.io/instance: "apps"
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/apps
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        {{ toYaml .Values | nindent 8 }}
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      {{- if .Values.spec.syncPolicy }}
      prune: true
      {{- end }}
      selfHeal: true
