{{- if index $.Values "apps" "argocd" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    argocd.argoproj.io/instance: apps
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/argocd
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        argo-cd:
          {{- index .Values "argo-cd" | toYaml | nindent 10 }}
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}
