{{- if index $.Values "apps" "argocd" "enabled" }}
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-99"
    {{- if index $.Values "apps" "argocd" "nodePool" }}
    scheduler.alpha.kubernetes.io/node-selector: "devops-stack.io/nodepool={{ index $.Values "apps" "argocd" "nodePool" }}"
    {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: "devops-stack"
  source:
    path: argocd/argocd
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        argo-cd:
          {{- index .Values "argo-cd" | toYaml | nindent 10 }}
        argocd-applicationset:
          {{- index .Values "argocd-applicationset" | toYaml | nindent 10 }}
        argocd-notifications:
          {{- index .Values "argocd-notifications" | toYaml | nindent 10 }}
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  {{- if .Values.spec.syncPolicy }}
  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
  {{- end }}
{{- end }}
