---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/argocd
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        clusterName: {{ .Values.spec.source.targetRevision }}
        # Enable metrics here because CRDs are not available at bootstrap
        argo-cd:
          controller:
            metrics:
              enabled: true
          server:
            metrics:
              enabled: true
          repoServer:
            metrics:
              enabled: true
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
