---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-monitoring
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/cluster-monitoring
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        baseDomain: {{ .Values.baseDomain }}
  destination:
    namespace: cluster-monitoring
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
