{{- if index $.Values "apps" "demo-app" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/demo-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: selfsigned-issuer
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: demo-app.apps.{{ .Values.baseDomain }}
              paths:
                - /
          tls:
            - secretName: demo-app-secret
              hosts:
                - demo-app.apps.{{ .Values.baseDomain }}
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 3
  destination:
    namespace: demo-app
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}
