{{- if index $.Values "apps" "keycloak" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  name: keycloak-operator
  namespace: argocd
spec:
  project: "devops-stack"
  source:
    path: deploy
    repoURL: https://github.com/keycloak/keycloak-operator.git
    targetRevision: 18.0.0
  destination:
    namespace: keycloak
    server: {{ .Values.spec.destination.server }}
  {{- if .Values.spec.syncPolicy }}
  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
  {{- end }}
{{- end }}
