{{- if index $.Values "apps" "keycloak" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  labels:
    argocd.argoproj.io/instance: apps
  name: keycloak-operator
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/keycloak-operator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: keycloak
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}
