{{- if index $.Values "apps" "kube-prometheus-stack" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/kube-prometheus-stack
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        kube-prometheus-stack:
          {{- index .Values "kube-prometheus-stack" | toYaml | nindent 10 }}
  destination:
    namespace: kube-prometheus-stack
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}
