{{- if index $.Values "apps" "loki" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/loki
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        loki:
          {{- index .Values "loki" | toYaml | nindent 10 }}
  destination:
    namespace: cluster-monitoring
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}
