{{- if index $.Values "apps" "metrics-server" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: "devops-stack"
  source:
    repoURL: https://github.com/kubernetes-sigs/metrics-server.git
    path: charts/metrics-server
    targetRevision: release-0.6
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  {{- if .Values.spec.syncPolicy }}
  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
  {{- end }}
{{- end }}
