{{- if .Values.namespaces }}
{{- range $ns, $annots := index .Values.namespaces }}
{{- $list := list }}
---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: {{ $ns | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "-99"
    {{- if and ($annots) (ne $ns "kube-prometheus-stack") (ne $ns "aad-pod-identity") (ne $ns "csi-secrets-store-provider-azure") (ne $ns "loki-stack")}}
    {{- range $k, $v := $annots }}
    {{- $list = append $list (printf "%s=%s" $k $v) }}
    {{- end }}
    scheduler.alpha.kubernetes.io/node-selector: {{ join ", " $list | quote }}
    {{- end }}
{{- end }}
{{- end }}
