{{- if index $.Values "apps" "namespaces" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: namespaces
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/namespaces
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}
