{{- if index $.Values "apps" "secrets-store-csi-driver" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  name: secrets-store-csi-driver
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/secrets-store-csi-driver
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: secrets-store-csi-driver
    server: {{ .Values.spec.destination.server }}
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: secretproviderclasses.secrets-store.csi.x-k8s.io
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: secretproviderclasspodstatuses.secrets-store.csi.x-k8s.io
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}
