{{- if index $.Values "apps" "telepresence" "enabled" }}
---
apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "traffic-manager"
  namespace: "argocd"
spec:
  project: "devops-stack"
  source:
    path: "argocd/telepresence"
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        telepresence:
          {{- index .Values "telepresence" | toYaml | nindent 10 }}
  destination:
    namespace: "ambassador"
    server: {{ .Values.spec.destination.server }}
  {{- if .Values.spec.syncPolicy }}
  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
  {{- end }}
{{- end }}
