{{- if index $.Values "apps" "vault" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/vault
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        vault:
          server:
            ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: selfsigned-issuer
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
              hosts:
                - host: vault.apps.{{ .Values.baseDomain }}
                  path: []
              tls:
                - secretName: vault-secret
                  hosts:
                    - vault.apps.{{ .Values.baseDomain }}
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}
