{{- if index $.Values "apps" "vault" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    path: argocd/vault
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        vault:
          {{- index .Values "vault" | toYaml | nindent 10 }}
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  {{- if .Values.spec.syncPolicy }}
  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
  {{- end }}
{{- end }}
