---
apps:
  local-path-provisioner:
    enabled: true
  metrics-server:
    enabled: false

argo-cd:
  server:
    extraArgs:
      - "--insecure"

cert-manager:
  tlsCrt: "${root_cert}"
  tlsKey: "${root_key}"
  clusterIssuers:
    letsencrypt:
      enabled: true
    acme:
      solvers:
        - http01:
            ingress: {}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: "node.exoscale.net/nodepool-id"
            operator: NotIn
            values:
            - "${router_pool_id}"
  cainjector:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: "node.exoscale.net/nodepool-id"
              operator: NotIn
              values:
              - "${router_pool_id}"
  webhook:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: "node.exoscale.net/nodepool-id"
              operator: NotIn
              values:
              - "${router_pool_id}"

loki-stack:
  promtail:
    extraScrapeConfigs:
      # Add an additional scrape config for syslog
      - job_name: "journal"
        journal:
          path: "/var/log/journal"
          max_age: "12h"
          labels:
            job: "systemd-journal"
        relabel_configs:
          - source_labels:
              - "__journal__systemd_unit"
            target_label: "unit"
          - source_labels:
              - "__journal__hostname"
            target_label: "hostname"

    # Mount journal directory into promtail pods
    extraVolumes:
      - name: "journal"
        hostPath:
          path: "/var/log/journal"

    extraVolumeMounts:
      - name: "journal"
        mountPath: "/var/log/journal"
        readOnly: true

traefik:
  ports:
    web:
      hostPort: 80
    websecure:
      hostPort: 443
  service:
    type: "NodePort"
