---
name: "commits-checks"

on: 
  pull_request:

jobs:
  commits-checks:
    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: "Check commit messages"
      uses: docker://aevea/commitsar
