---
name: "release-please"

on:
  push:
    branches:
    - "main"

jobs:
  release-please:
    runs-on: "ubuntu-latest"

    steps:
    - uses: "google-github-actions/release-please-action@v3"
      id: "release-please"
      with:
        release-type: "simple"
        pull-request-title-pattern: "chore: release ${version}"
        bump-minor-pre-major: true
        extra-files: |
          modules/variables.tf
          docs/antora.yml

    outputs:
      release_created: "${{ steps.release-please.outputs.release_created }}"

  publish-documentation:
    needs:
    - "release-please"
    if: "needs.release-please.outputs.release_created"
    uses: "./.github/workflows/documentation.yaml"
