---
name: test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd examples/k3s-docker-demo-app && make
      - run: cd examples/k3s-docker-demo-app && make clean
