---
name: "Website"

on:
  pull_request:
    paths:
      - "site/**"

  push:
    branches:
      - "master"

    paths:
      - "site/**"

jobs:
  build:
    name: "Build website with Hugo"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          submodules: true # Fetch Hugo theme
          fetch-depth: 0   # Fetch all history for .GitInfo and .Lastmod

      - name: "Setup Hugo"
        uses: "peaceiris/actions-hugo@v2"
        with:
          hugo-version: "0.92.2"
          extended: true

      - name: "Build"
        run: "hugo --minify --source 'site'"

      - name: "Upload generated artifact"
        uses: "actions/upload-artifact@v2"
        with:
          name: "website"
          path: "${{ github.workspace }}/build/site"

  deploy:
    name: "Deploy website to GitHub Pages"
    if: "github.event_name == 'push'"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Download generated artifact"
        uses: "actions/download-artifact@v2"
        with:
          name: "website"

      - name: "Deploy to GitHub Pages"
        uses: "JamesIves/github-pages-deploy-action@v4.2.5"
        with:
          branch: "gh-pages"
          folder: "."
          commit-message: "ci: publish website for ${{ github.sha }}"
          clean-exclude: |
            CNAME
            .nojekyll
