---
name: "Website"

on:
  pull_request:
    paths:
      - "website/**"

  push:
    branches:
      - "master"

    paths:
      - "website/**"

  workflow_dispatch:

jobs:
  publish:
    name: "Publish website"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          submodules: true # Fetch Hugo theme
          fetch-depth: 0   # Fetch all history for .GitInfo and .Lastmod

      - name: "Setup Hugo"
        uses: "peaceiris/actions-hugo@v2"
        with:
          hugo-version: "0.92.2"
          extended: true

      - name: "Build website with Hugo"
        run: "hugo --minify --source 'website' --destination '../public'"

      - name: "Upload generated artifact"
        if: "github.event_name == 'pull_request'"
        uses: "actions/upload-artifact@v2"
        with:
          name: "website"
          path: "${{ github.workspace }}/public"

      - name: "Deploy website to GitHub Pages"
        if: "(github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'master'"
        uses: "JamesIves/github-pages-deploy-action@v4.2.5"
        with:
          branch: "gh-pages"
          folder: "public"
          commit-message: "ci: publish website for ${{ github.sha }}"
          clean-exclude: |
            docs
